resume:
save_dir: models/
log_dir: ${name}/

metrics:
  - _target_: srcs.model.metric.accuracy
  - _target_: srcs.model.metric.top_k_acc

defaults:
  - _self_
  - data: mnist_train
  - model: mnist_lenet
  - hparams: lenet_baseline

  - status: train

  - working_dir: job_timestamp
  - override hydra/job_logging : custom
